### ISSUE TITLE
Fix some documentation (README)

### ISSUE THREAD

**Issue by Zykino** [ludiazv/node-nrf24#11]
Import
`const nrf24=require("nRF24"); // Load de module` -> `const nrf24=require("nrf24"); // Load de module` or `import * as nrf24 from 'nrf24';`

Constructor
`var rf24= new nrf24.RF24(<CE gpio>,<CS gpio>);` -> `this.rf24 = new nrf24.nRF24(22, 0)`

**Comment by ludiazv** [comment]
Fixed.

PR are open if you spot any other error.

Thnx.
