### ISSUE TITLE
Does not work with node 12

### ISSUE THREAD

**Issue by pavelnikitiuk** [ludiazv/node-nrf24#18]
does not compile with node 12 due to the use of outdated libraries, see details here https://github.com/ludiazv/node-red-contrib-nrf24/issues/4

**Comment by jojos38** [comment]
Did you find any fix by the time please?

**Comment by ludiazv** [comment]
Yes, we have found the problem but not implemented the solution yet. I had no time do it in the past months. I will try  by next week.

**Comment by ludiazv** [comment]
Good news, 
  I've found some time to fix this. I removed the dependency of nan-marshal al copied @pavelnikitiuk  version with minor modifications to the project tree. As the original author of marshal did not update the module in npm.

 This with some minor fixes in the code enable the library to be used with node 8, 10 , 12. Im working in a travis build to automate the check against this versions for arm32 and arm64 platforms. So it will be easy to spot failures with future node versions. 

Changes are nor in the master branch, I will publish a new version in npm when travis build is ready.

Thanks for your contribution.

**Comment by jojos38** [comment]
Thank you very much! I can't wait to have the npm version, for now I believe I can download this repo and use npm install [folder of this repo I downloaded]?
Edit: yep worked

**Comment by ludiazv** [comment]
I will publish the new version soon in npm so it can be installed via usual npm install

**Comment by jojos38** [comment]
Okay thank you!

**Comment by ludiazv** [comment]
Released 0.1.5 on npmjs. Now it can be installed via npm install method. 
I checked it with node 10, 12, 13
