### ISSUE TITLE
test_simple.js Syntax error

### ISSUE THREAD

**Issue by leyaX** [ludiazv/node-nrf24#19]
tested on raspberry pi 3 B + "raspian buster"

The two RF24 modules connect well together, but I get this error when the server receives

`/home/pi/NODE/node_modules/nrf24/test/test_simple.js:36
  rfo.write(d); // Pong back
      ^

SyntaxError: Unknown error
    at /home/pi/NODE/node_modules/nrf24/test/test_simple.js:36:7
`

**Comment by ludiazv** [comment]
This test is not updated for the last versions of the library. If you want a simple go to examples -> gettingstarted
