### ISSUE TITLE
Most settings not being displayed correctly

### ISSUE THREAD

**Issue by jojos38** [ludiazv/node-nrf24#21]
PA Power    = PA_MIN
IRQ (negative is unused):-1
PayloadSize:32

That's not the full list but a lot of settings are not showed their real values, tho the values I used are indeed applied

**Comment by ludiazv** [comment]
could you please post your example and output?

**Comment by jojos38** [comment]
Here is a video
https://www.youtube.com/watch?v=YZ1onV1Fmj4

**Comment by ludiazv** [comment]
you are showing the radio configuration in begin.
by radio.begin(true). This is used for debug that the radio is connected and always will show default configuration of the radio. change this to radio.begin(false)

If you want to show the radio parameters after config. call radio.config({..},true)
this will show the radio configuration after config.

check it out

**Comment by jojos38** [comment]
Oh okay! Thank you!
