### ISSUE TITLE
NPM Install fails

### ISSUE THREAD

**Issue by jackjury** [ludiazv/node-nrf24#22]
Hello, 

I have just tried to install this on a raspberry pi, and the install fails, log file below... any ideas?

I have tried running the install command as sudo

**Comment by jackjury** [comment]
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'nrf24',
1 verbose cli   '--save' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose npm-session 8913e67e3ea60600
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/nrf24 2767ms (from cache)
8 silly pacote tag manifest for nrf24@latest fetched in 3320ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule nrf24@0.1.5-beta checking installable status
14 http fetch GET 304 https://registry.npmjs.org/bindings 1243ms (from cache)
15 silly pacote range manifest for bindings@^1.5.0 fetched in 1324ms
16 silly resolveWithNewModule bindings@1.5.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/nan-check 1310ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/nan 1343ms (from cache)
19 silly pacote version manifest for nan-check@0.0.6 fetched in 1407ms
20 silly resolveWithNewModule nan-check@0.0.6 checking installable status
21 silly pacote range manifest for nan@^2.14.0 fetched in 1447ms
22 silly resolveWithNewModule nan@2.14.1 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 575ms (from cache)
24 silly pacote version manifest for file-uri-to-path@1.0.0 fetched in 648ms
25 silly resolveWithNewModule file-uri-to-path@1.0.0 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/nan-marshal 296ms (from cache)
27 silly pacote version manifest for nan-marshal@0.0.5 fetched in 334ms
28 silly resolveWithNewModule nan-marshal@0.0.5 checking installable status
29 silly currentTree tempmonnode@1.0.0
29 silly currentTree ├── bindings@1.2.1
29 silly currentTree ├── epoll@0.1.22
29 silly currentTree ├── fifolock@1.0.0
29 silly currentTree ├── nan@2.6.2
29 silly currentTree ├── nrf@0.8.3
29 silly currentTree ├── pi-pins@1.0.2
29 silly currentTree ├─┬ pi-spi@1.2.1
29 silly currentTree │ └── nan@2.14.1
29 silly currentTree └── queue-async@1.0.7
30 silly idealTree tempmonnode@1.0.0
30 silly idealTree ├── bindings@1.2.1
30 silly idealTree ├── epoll@0.1.22
30 silly idealTree ├── fifolock@1.0.0
30 silly idealTree ├── file-uri-to-path@1.0.0
30 silly idealTree ├── nan-check@0.0.6
30 silly idealTree ├── nan-marshal@0.0.5
30 silly idealTree ├── nan@2.6.2
30 silly idealTree ├── nrf@0.8.3
30 silly idealTree ├─┬ nrf24@0.1.5-beta
30 silly idealTree │ ├── bindings@1.5.0
30 silly idealTree │ └── nan@2.14.1
30 silly idealTree ├── pi-pins@1.0.2
30 silly idealTree ├─┬ pi-spi@1.2.1
30 silly idealTree │ └── nan@2.14.1
30 silly idealTree └── queue-async@1.0.7
31 silly install generateActionsToTake
32 silly diffTrees action count 6
33 silly diffTrees add file-uri-to-path@1.0.0
34 silly diffTrees add nan-marshal@0.0.5
35 silly diffTrees add nan-check@0.0.6
36 silly diffTrees add bindings@1.5.0
37 silly diffTrees add nan@2.14.1
38 silly diffTrees add nrf24@0.1.5-beta
39 silly decomposeActions action count 48
40 silly decomposeActions fetch file-uri-to-path@1.0.0
41 silly decomposeActions extract file-uri-to-path@1.0.0
42 silly decomposeActions preinstall file-uri-to-path@1.0.0
43 silly decomposeActions build file-uri-to-path@1.0.0
44 silly decomposeActions install file-uri-to-path@1.0.0
45 silly decomposeActions postinstall file-uri-to-path@1.0.0
46 silly decomposeActions finalize file-uri-to-path@1.0.0
47 silly decomposeActions refresh-package-json file-uri-to-path@1.0.0
48 silly decomposeActions fetch nan-marshal@0.0.5
49 silly decomposeActions extract nan-marshal@0.0.5
50 silly decomposeActions preinstall nan-marshal@0.0.5
51 silly decomposeActions build nan-marshal@0.0.5
52 silly decomposeActions install nan-marshal@0.0.5
53 silly decomposeActions postinstall nan-marshal@0.0.5
54 silly decomposeActions finalize nan-marshal@0.0.5
55 silly decomposeActions refresh-package-json nan-marshal@0.0.5
56 silly decomposeActions fetch nan-check@0.0.6
57 silly decomposeActions extract nan-check@0.0.6
58 silly decomposeActions preinstall nan-check@0.0.6
59 silly decomposeActions build nan-check@0.0.6
60 silly decomposeActions install nan-check@0.0.6
61 silly decomposeActions postinstall nan-check@0.0.6
62 silly decomposeActions finalize nan-check@0.0.6
63 silly decomposeActions refresh-package-json nan-check@0.0.6
64 silly decomposeActions fetch bindings@1.5.0
65 silly decomposeActions extract bindings@1.5.0
66 silly decomposeActions preinstall bindings@1.5.0
67 silly decomposeActions build bindings@1.5.0
68 silly decomposeActions install bindings@1.5.0
69 silly decomposeActions postinstall bindings@1.5.0
70 silly decomposeActions finalize bindings@1.5.0
71 silly decomposeActions refresh-package-json bindings@1.5.0
72 silly decomposeActions fetch nan@2.14.1
73 silly decomposeActions extract nan@2.14.1
74 silly decomposeActions preinstall nan@2.14.1
75 silly decomposeActions build nan@2.14.1
76 silly decomposeActions install nan@2.14.1
77 silly decomposeActions postinstall nan@2.14.1
78 silly decomposeActions finalize nan@2.14.1
79 silly decomposeActions refresh-package-json nan@2.14.1
80 silly decomposeActions fetch nrf24@0.1.5-beta
81 silly decomposeActions extract nrf24@0.1.5-beta
82 silly decomposeActions preinstall nrf24@0.1.5-beta
83 silly decomposeActions build nrf24@0.1.5-beta
84 silly decomposeActions install nrf24@0.1.5-beta
85 silly decomposeActions postinstall nrf24@0.1.5-beta
86 silly decomposeActions finalize nrf24@0.1.5-beta
87 silly decomposeActions refresh-package-json nrf24@0.1.5-beta
88 silly install executeActions
89 silly doSerial global-install 48
90 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
91 verbose lock using /root/.npm/_locks/staging-6881afea7e7f6dc4.lock for /home/pi/v4node/node_modules/.staging
92 silly doParallel extract 48
93 silly extract file-uri-to-path@1.0.0
94 silly pacote trying file-uri-to-path@https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz by hash: sha512-0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==
95 silly extract nan-marshal@0.0.5
96 silly pacote trying nan-marshal@https://registry.npmjs.org/nan-marshal/-/nan-marshal-0.0.5.tgz by hash: sha1-DUoDXpP0WsfyNhPZZjZ/QvsYLPY=
97 silly extract nan-check@0.0.6
98 silly pacote trying nan-check@https://registry.npmjs.org/nan-check/-/nan-check-0.0.6.tgz by hash: sha1-i/0uecNkOSgPpKl11BgkxaLSv6U=
99 silly extract bindings@1.5.0
100 silly pacote trying bindings@https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz by hash: sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==
101 silly extract nan@2.14.1
102 silly pacote trying nan@https://registry.npmjs.org/nan/-/nan-2.14.1.tgz by hash: sha512-isWHgVjnFjh2x2yuJ/tj3JbwoHu3UC2dX5G/88Cm24yB6YopVgxvBObDY7n5xW6ExmFhJpSEQqFPvq9zaXc8Jw==
103 silly extract nrf24@0.1.5-beta
104 silly pacote trying nrf24@https://registry.npmjs.org/nrf24/-/nrf24-0.1.5-beta.tgz by hash: sha512-1MLvGicbv/ktvoE6W7uEbhT1WdEJ1GUqJUXORPQ94RR1GQa/CAtmi4GElujnnTxAZyhqx25nT98KTzAAtEOvnw==
105 silly pacote bindings@https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz extracted to /home/pi/v4node/node_modules/.staging/bindings-95e0f43f by content address 2014ms
106 silly pacote file-uri-to-path@https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz extracted to /home/pi/v4node/node_modules/.staging/file-uri-to-path-aaacfaef by content address 2361ms
107 silly pacote nan-marshal@https://registry.npmjs.org/nan-marshal/-/nan-marshal-0.0.5.tgz extracted to /home/pi/v4node/node_modules/.staging/nan-marshal-fc2a0c3b by content address 3351ms
108 silly pacote nan-check@https://registry.npmjs.org/nan-check/-/nan-check-0.0.6.tgz extracted to /home/pi/v4node/node_modules/.staging/nan-check-4de642f8 by content address 3924ms
109 silly pacote nan@https://registry.npmjs.org/nan/-/nan-2.14.1.tgz extracted to /home/pi/v4node/node_modules/.staging/nan-a65b7c0f by content address 3993ms
110 silly pacote nrf24@https://registry.npmjs.org/nrf24/-/nrf24-0.1.5-beta.tgz extracted to /home/pi/v4node/node_modules/.staging/nrf24-3683fb31 by content address 4180ms
111 silly doReverseSerial unbuild 48
112 silly doSerial remove 48
113 silly doSerial move 48
114 silly doSerial finalize 48
115 silly finalize /home/pi/v4node/node_modules/file-uri-to-path
116 silly finalize /home/pi/v4node/node_modules/nan-marshal
117 silly finalize /home/pi/v4node/node_modules/nan-check
118 silly finalize /home/pi/v4node/node_modules/nrf24/node_modules/bindings
119 silly finalize /home/pi/v4node/node_modules/nrf24/node_modules/nan
120 silly finalize /home/pi/v4node/node_modules/nrf24
121 silly doParallel refresh-package-json 48
122 silly refresh-package-json /home/pi/v4node/node_modules/file-uri-to-path
123 silly refresh-package-json /home/pi/v4node/node_modules/nan-marshal
124 silly refresh-package-json /home/pi/v4node/node_modules/nan-check
125 silly refresh-package-json /home/pi/v4node/node_modules/nrf24/node_modules/bindings
126 silly refresh-package-json /home/pi/v4node/node_modules/nrf24/node_modules/nan
127 silly refresh-package-json /home/pi/v4node/node_modules/nrf24
128 silly doParallel preinstall 48
129 silly preinstall file-uri-to-path@1.0.0
130 info lifecycle file-uri-to-path@1.0.0~preinstall: file-uri-to-path@1.0.0
131 silly preinstall nan-marshal@0.0.5
132 info lifecycle nan-marshal@0.0.5~preinstall: nan-marshal@0.0.5
133 silly preinstall nan-check@0.0.6
134 info lifecycle nan-check@0.0.6~preinstall: nan-check@0.0.6
135 silly preinstall bindings@1.5.0
136 info lifecycle bindings@1.5.0~preinstall: bindings@1.5.0
137 silly preinstall nan@2.14.1
138 info lifecycle nan@2.14.1~preinstall: nan@2.14.1
139 silly preinstall nrf24@0.1.5-beta
140 info lifecycle nrf24@0.1.5-beta~preinstall: nrf24@0.1.5-beta
141 verbose lifecycle nrf24@0.1.5-beta~preinstall: unsafe-perm in lifecycle false
142 verbose lifecycle nrf24@0.1.5-beta~preinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/v4node/node_modules/nrf24/node_modules/.bin:/home/pi/v4node/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
143 verbose lifecycle nrf24@0.1.5-beta~preinstall: CWD: /home/pi/v4node/node_modules/nrf24
144 silly lifecycle nrf24@0.1.5-beta~preinstall: Args: [ '-c', './build_rf24libs.sh' ]
145 silly lifecycle nrf24@0.1.5-beta~preinstall: Returned: code: 1  signal: null
146 info lifecycle nrf24@0.1.5-beta~preinstall: Failed to exec preinstall script
147 verbose unlock done using /root/.npm/_locks/staging-6881afea7e7f6dc4.lock for /home/pi/v4node/node_modules/.staging
148 warn tempmonnode@1.0.0 No repository field.
149 verbose stack Error: nrf24@0.1.5-beta preinstall: `./build_rf24libs.sh`
149 verbose stack Exit status 1
149 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
149 verbose stack     at emitTwo (events.js:126:13)
149 verbose stack     at EventEmitter.emit (events.js:214:7)
149 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
149 verbose stack     at emitTwo (events.js:126:13)
149 verbose stack     at ChildProcess.emit (events.js:214:7)
149 verbose stack     at maybeClose (internal/child_process.js:925:16)
149 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
150 verbose pkgid nrf24@0.1.5-beta
151 verbose cwd /home/pi/v4node
152 verbose Linux 4.19.97+
153 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nrf24" "--save"
154 verbose node v8.9.0
155 verbose npm  v5.5.1
156 error code ELIFECYCLE
157 error errno 1
158 error nrf24@0.1.5-beta preinstall: `./build_rf24libs.sh`
158 error Exit status 1
159 error Failed at the nrf24@0.1.5-beta preinstall script.
159 error This is probably not a problem with npm. There is likely additional logging output above.
160 verbose exit [ 1, true ]
`

**Comment by jackjury** [comment]
[fail.log](https://github.com/ludiazv/node-nrf24/files/4587785/fail.log)

**Comment by ludiazv** [comment]
Hi did you tried with node >=10?

**Comment by jackjury** [comment]
Yes I have now thank you, its still not 100% working, but I'll close this issue!
