### ISSUE TITLE
Channel 0 doesn't work

### ISSUE THREAD

**Issue by Marsu31** [ludiazv/node-nrf24#27]
Hi !

The channel 0 is not taken into account, it is replaced by default 76.
The line 189 in `rf24_setup.cc` seems to test the range [1;127] instead of [0;126].

Regards.

**Comment by ludiazv** [comment]
Hi,
  You are right. Fixed it will be availebe in the next release.

**Comment by Marsu31** [comment]
Thank you ! ^^
