### ISSUE TITLE
Packages arrive only when auto_ack: true

### ISSUE THREAD

**Issue by tobiasmuecksch** [ludiazv/node-nrf24#3]
I'm having a sender and a receiver.

The sender constantly sends packages, and the receiver prints out the number of packages received per second. 

When I disable auto_ack, **less than 1%** of the packages arrive.
Only when auto_ack is enabled, all the packages arrive.

I assumed that at least 50% of the packages will arrive. But less than 1% seem strange to me.
Is that normal?

**Comment by ludiazv** [comment]
Hi,
  This seems like a error. Could you share your code to do some test?

Regards,

**Comment by tobiasmuecksch** [comment]
I've created a repository with my test code for you:
https://github.com/tobiasmuecksch/NRF24-test

I've written a wrapper for this library; therefore there are two kinds of tests (with and without the wrapper).

**Comment by ludiazv** [comment]
I have tested your code and found on problem on the library. The writingPipe is always configured for AutoAck. I did some modifications so now you set up the writting pipe with no Auto Ack.

I've have also make this optional parameters. I will do some addtional testing and commit the changes.
This should solve the issue.

**Comment by ludiazv** [comment]
I've tested this bug and works well. It should be ready in the next release.

Regards,

**Comment by tobiasmuecksch** [comment]
@ludiazv Thank you so much, for your awesome work!

**Comment by ludiazv** [comment]
@tobiasmuecksch I just uploaded a new version to the master branch. It should work now with and without Ack. The API has improved. But it has breaking changes on ``read`` method. Now it receives an array.

Could check if you are able to send and receive without ACK.

**Comment by tobiasmuecksch** [comment]
@ludiazv Thank you very much for your effort. I will test it next week!
