### ISSUE TITLE
Error writing to pipe depending on scope

### ISSUE THREAD

**Issue by gedeondt** [ludiazv/node-nrf24#31]
Hi,

   I am having an issue regarding this code:

          var nrf24=require("nrf24");
          var readline = require('linebyline');
          var rf24= new nrf24.nRF24(174, 20);
          console.log("begin->",rf24.begin(true));
          rf24.useWritePipe("0x72646f4e31");
          var rl = readline(process.stdin);
          
          rl.on('line', function(line){
                  success = rf24.write(Buffer.from(line));  ------------> This write works
                  console.log("Sent " + ( success ? "OK" : "KO" ));
          });
          
          success = rf24.write("ASD");    ---> This fails: SyntaxError: Unknown error

      I can't see the difference between both. It's weird.

**Comment by ludiazv** [comment]
Hi,
   ```write``` requires a node Buffer as parameter. The SyntaxError is produced by the library as you passed a string in the second call. ```success = rf24.write(Buffer.from("ASD"));``` should work.

**Comment by gedeondt** [comment]
Hi,

    Thanks! My fault.

    Closed.
