### ISSUE TITLE
usb adapter

### ISSUE THREAD

**Issue by ptorrent** [ludiazv/node-nrf24#36]
Hello there !

Is there a way to use this library with an USB adapter ?

CH340T USB + 2.4G NRF24L01 (ch341-uart)

Thanks for your help !

**Comment by ludiazv** [comment]
No. This module require SPI connection with the module.  AFAIK CH340 is a USB<->UART chip that won't be able to communicate with the NRF24 module as it requires a SPI interface.

To connect this module to an usb a USB-> SPI is required. But also in that case this package will not be able to work unless the driver of the module exposes a /dev/spidev interface at OS level.
