### ISSUE TITLE
radio.resetStats() does not reset stats

### ISSUE THREAD

**Issue by ngfelixl** [ludiazv/node-nrf24#8]
Hi,

I think the `resetStats()` function isn't working as it should. Using it in an interval reading the stats and resetting it afterwards will not reset the stats.

```typescript
setInterval(() => {
  console.log(this.radio.getStats()); // works properly { TotalTx_Ok: #, etc... }
  this.radio.resetStats();
}, 500);
```

As a workaround one could use the difference of two steps, but that's not intended for using the lib I think, so I thought it might be a good idea to open an issue.

Thanks again for your great work and support!

**Comment by ludiazv** [comment]
Hi,
  Very strange, as this function si quite simple. I will check if missed something.

Regards,

**Comment by ludiazv** [comment]
It should be fixed now in master branch.
